---
- hosts: 192.168.122.1
  remote_user: root
  tasks:

    - name: Install httpd package
      yum: name=httpd state=latest
      sudo: yes


    - name: starting https service
      service: name=httpd state=started
      sudo: yes